version: '3.8'

services:
 auth-db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: auth-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Click@123RaoHammad*1
    ports:
      - "1434:1433"
    networks:
      - microservice-network
    volumes:
      - auth_db_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Click@123RaoHammad*1", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
  # auth-db:
  #   image: mcr.microsoft.com/mssql/server:2025-latest
  #   container_name: auth-db
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Click@123RaoHammad*1
  #   ports:
  #     - "1434:1433"
  #   networks:
  #     - microservice-network
  #   restart: always

networks:
  microservice-network:
    external: true

volumes:
  auth_db_data:
    external: true
