spring.application.name=auth-service
server.port=8081


# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=skynetWafiUserAuthDB;encrypt=false;trustServerCertificate=true
springdoc.use-management-port=false

springdoc.show-actuator=false

springdoc.api-docs.enabled=true
springdoc.default-produces-media-type=application/json
springdoc.override-with-generic-response=false
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


server.forward-headers-strategy = native

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.kafka.producer.max-request-size=20971520
# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update 
# spring.jpa.hibernate.ddl-auto=validate 

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true


# Logging
logging.level.org.springframework.security=DEBUG

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.paths-to-match=/**
springdoc.api-docs.server-url=http://127.0.0.1:8080/auth-service


# Feign client settings
feign.client.config.USER-SERVICE.loggerLevel=full
feign.client.config.USER-SERVICE.connectTimeout=5000
feign.client.config.USER-SERVICE.readTimeout=5000

# Compatibility workaround
spring.cloud.compatibility-verifier.enabled=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_A_EXPIRATION}

# spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=localhost:9092

# Optional: to use JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
hashid.salt=${HASHID_SALT}
hashid.min-length=8
kafka.topics.user-events=logs
app.jwt.refresh-token-duration-ms=604800000