200=User logged in successfully
201=User registered successfully
202=Logged out successfully
203=Distributions retrieved successfully
204=Roles retrieved successfully
205=Successfully updated user
206=Successfully fetched all users

400=Invalid or Incomplete Input
401=You are unauthorized for this action.
402=Some, or all, of your provided Role IDs are invalid
403=Some, or all, of your provided Permission IDs are invalid
404=User not found
405=Some, or all, of your provided Distribution IDs are invalid
406=Some, or all, of your provided User IDs are invalid
407=Username not found
408=The JWT token that you have provided is invalid
409=Invalid email or password

500=Internal Server Error
502=Email already used